.\" Manpage for qclient.
.\" Written by Cameron Cook
.TH "18 Feb 2019" "qclient man page"
.SH NAME
qclient - question bank client 
.SH SYNOPSIS
"./qclient [hostname] [port]"
.SH DESCRIPTION
Starts the question bank client. Commands can then be written to the server to write, delete, check, and get questions (among other). Once the program is running, you can see a full list of commands by typing 'h'
.SH OPTIONS
Hostname - the host the server is running on
port - the port the server is running on
.SH SEE ALSO
qserver
.SH BUGS
No known bugs, most errors are handled but some are unchecked (such as question formatting)
.SH AUTHOR
Cameron Cook